### ISSUE TITLE
"No popup available" while popup exist - Prestashop  1.7.8.5

### ISSUE THREAD

**Issue by celi28** [TeamEver/everpspopup#1]
Hello,
While trying to install and configure this module, I found the following issue

**Describe the issue:** Popup is configured to be displayed on all pages, cookie lifetime set to disable.
While browsing pages, browser console drop an information message.
```
JQMIGRATE: Migrate is installed, version 3.1.0 [bottom-81304d6.js:1:36430](https://shop.oelabs.co/themes/classic/assets/cache/bottom-81304d6.js)
No popup available
```

**Current stack**: Prestashop 1.7.8.5 + Module v5.2.3
Fancybox disabled (enabled doesn't change anything). Popup configured as id 2 and activated.

**Comment by CySSoO** [comment]
Hello
I just released an update to the mod. Can you install it?
Following this, it will be necessary to recheck the client groups, do not hesitate to reset the module so that it can be fully operational

**Comment by celi28** [comment]
Hello,
Got an `invalid module zip file` while uploading the release zip

**Comment by CySSoO** [comment]
It is not possible to upload a module from Github directly to Prestashop. In your case, you must rename the name of the directory of the module contained in the archive, to rename it to "everpspopup", then compress the directory and then upload to the store.
You can also upload the module content in /modules/everpspopup on your store

**Comment by celi28** [comment]
Works fine. Thanks a lot :)
