### ISSUE TITLE
The second popup does not work

### ISSUE THREAD

**Issue by marinovivaylo** [TeamEver/everpspopup#3]
In one ps1.6 site I have created 2 popups for two different categories. The first one works without problems, but the second one doesn't show up at all.
In principle, does the module allow one popup to have a cookie for 1 day and the other for 7 days for example ?

**Comment by CySSoO** [comment]
Good morning
By default, the cookie lifetime is global
This module will however no longer be supported from Prestashop 1.7 in favor of Everblock, which in turn allows more functionalities and includes almost all of the functionalities of Everpopup
You can find Everblock here
[https://github.com/TeamEver/everblock](https://github.com/TeamEver/everblock)

**Comment by marinovivaylo** [comment]
Everblock is very nice, but does not support prestashop 1.6
The problem with everpopup is that 2 popups cannot work at the same time, for 2 different categories. If the first one is stopped, the second one starts working normally. 
Ok I will look for another solution. 
Thanks for the nice modules you make.
